export const availableIngredients = [
  { name: "Kaiser Bun", color: "lightpink" },
  { name: "Sesame Bun", color: "lightgoldenrodyellow" },
  { name: "Gluten Free Bun", color: "peachpuff" },
  { name: "Lettuce Wrap", color: "lightseagreen" },
  { name: "Beef Patty", color: "mistyrose" },
  { name: "Soy Patty", color: "mistyrose" },
  { name: "Black Bean Patty", color: "lavender" },
  { name: "Chicken Patty", color: "lightcoral" },
  { name: "Lettuce", color: "lightgreen" },
  { name: "Tomato", color: "lightcoral" },
  { name: "Bacon", color: "lightpink" },
  { name: "Onion", color: "paleturquoise" },
  { name: "Cheddar Cheese", color: "peachpuff" },
  { name: "Swiss Cheese", color: "lightyellow" },
];
